# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "weathercli — reporte del clima en la terminal";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-unstable";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
          in
          {
            packages = {
              weathercli = pkgs.stdenv.mkDerivation {
                pname = "weathercli";
                version = "1.0.0";
                src = ./.;
                nativeBuildInputs = [ pkgs.makeWrapper ];
                dontConfigure = true;
                dontBuild = true;
                installPhase = "\n            mkdir -p $out/bin $out/share/weathercli\n            install -m755 weathercli.sh $out/bin/weathercli\n            install -m644 ${pkgs.writeText "weathercli-config.json" "{\"city\":\"Tokyo\",\"units\":\"metric\",\"format\":\"compact\"}"} $out/share/weathercli/config.json\n        ";
                postFixup = "for f in \"$out\"/bin/*; do\n  wrapProgram \"$f\" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.curl pkgs.jq ]}\ndone\n\n            wrapProgram $out/bin/weathercli                 --set-default WEATHERCLI_CONFIG $out/share/weathercli/config.json\n        ";
              };
            };
          };
      };
    in
    {
      packages = builtins.mapAttrs (_: s: s.packages) perSystem;
    };
}
